/* eslint-disable */
// @ts-nocheck
// biome-ignore-all lint: auto-generated
// Auto-generated by @vite-env/core
// Do not edit manually — re-generated on every dev server start and build

declare module 'virtual:env/client' {
  const env: {

  }
  export { env }
  export default env
}

declare module 'virtual:env/server' {
  const env: {
    readonly S3_IMAGES_BUCKET: string
    readonly S3_AGENTS_BUCKET: string
    readonly S3_REGION: string
    readonly S3_ENDPOINT: string
    readonly S3_ACCESS_KEY_ID: string
    readonly S3_SECRET_ACCESS_KEY: string
  }
  export { env }
  export default env
}
