/* eslint-disable */
// @ts-nocheck
// biome-ignore-all lint: auto-generated
// Auto-generated by @vite-env/core
// Do not edit manually — re-generated on every dev server start and build

declare module 'virtual:env/client' {
  const env: {
    readonly VITE_APP_NAME: string
    readonly VITE_CONSOLE_URL: string
    readonly VITE_DOCS_URL: string
    readonly VITE_WEB_URL: string
    readonly VITE_DEBUG: boolean
  }
  export { env }
  export default env
}

declare module 'virtual:env/server' {
  const env: {
    readonly OPENROUTER_API_KEY: string
    readonly OPENROUTER_MODEL: string
    readonly VITE_APP_NAME: string
    readonly VITE_CONSOLE_URL: string
    readonly VITE_DOCS_URL: string
    readonly VITE_WEB_URL: string
    readonly VITE_DEBUG: boolean
  }
  export { env }
  export default env
}
