/* eslint-disable */
// @ts-nocheck
// biome-ignore-all lint: auto-generated
// Auto-generated by @vite-env/core
// Do not edit manually — re-generated on every dev server start and build

declare module 'virtual:env/client' {
  const env: {
    readonly VITE_APP_NAME: string
    readonly VITE_CONSOLE_URL: string
    readonly VITE_DOCS_URL: string
    readonly VITE_WEB_URL: string
    readonly VITE_DEBUG: boolean
    readonly VITE_GITHUB_REPO: string
    readonly VITE_GITHUB_OWNER: string
    readonly VITE_DOCS_CATEGORY: string
  }
  export { env }
  export default env
}

declare module 'virtual:env/server' {
  const env: {
    readonly OPENROUTER_API_KEY: string
    readonly OPENROUTER_MODEL: string
    readonly GITHUB_APP_ID: string
    readonly GITHUB_APP_PRIVATE_KEY: string
    readonly GITHUB_APP_WEBHOOK_SECRET?: string
    readonly VITE_APP_NAME: string
    readonly VITE_CONSOLE_URL: string
    readonly VITE_DOCS_URL: string
    readonly VITE_WEB_URL: string
    readonly VITE_DEBUG: boolean
    readonly VITE_GITHUB_REPO: string
    readonly VITE_GITHUB_OWNER: string
    readonly VITE_DOCS_CATEGORY: string
  }
  export { env }
  export default env
}
