/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as app2RouteRouteImport } from './routes/(app2)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiImagesRouteImport } from './routes/api/images'
import { Route as ApiFilesTestRouteImport } from './routes/api/files-test'
import { Route as ApiFilesRouteImport } from './routes/api/files'
import { Route as publicVersionRouteImport } from './routes/(public)/version'
import { Route as publicThemeRouteImport } from './routes/(public)/theme'
import { Route as publicAboutRouteImport } from './routes/(public)/about'
import { Route as app2Dashboard2RouteImport } from './routes/(app2)/dashboard2'
import { Route as appRenewalsRouteImport } from './routes/(app)/renewals'
import { Route as appOrdersRouteImport } from './routes/(app)/orders'
import { Route as ApiChatIndexRouteImport } from './routes/api/chat/index'
import { Route as appSupportIndexRouteImport } from './routes/(app)/support/index'
import { Route as appDashboardIndexRouteImport } from './routes/(app)/dashboard/index'
import { Route as ApiHealthLiveRouteImport } from './routes/api/health/live'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as publicAuthPathRouteImport } from './routes/(public)/auth/$path'
import { Route as appSettingsNotificationsRouteImport } from './routes/(app)/settings/notifications'
import { Route as appSettingsPageRouteImport } from './routes/(app)/settings/$page'
import { Route as appReportsPageRouteImport } from './routes/(app)/reports.$page'
import { Route as appPlaygroundWorkflowRouteImport } from './routes/(app)/playground/workflow'
import { Route as appPlaygroundTestRouteImport } from './routes/(app)/playground/test'
import { Route as appPlaygroundFormDemoRouteImport } from './routes/(app)/playground/form-demo'
import { Route as appPlaygroundFilesRouteImport } from './routes/(app)/playground/files'
import { Route as appPlaygroundErrorRouteImport } from './routes/(app)/playground/error'
import { Route as appDashboardPageRouteImport } from './routes/(app)/dashboard/$page'
import { Route as appAdminPageRouteImport } from './routes/(app)/admin.$page'
import { Route as appsecurityUserPathRouteImport } from './routes/(app)/(security)/user.$path'
import { Route as appsecurityOrganizationPathRouteImport } from './routes/(app)/(security)/organization.$path'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const app2RouteRoute = app2RouteRouteImport.update({
  id: '/(app2)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesRoute = ApiImagesRouteImport.update({
  id: '/api/images',
  path: '/api/images',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesTestRoute = ApiFilesTestRouteImport.update({
  id: '/api/files-test',
  path: '/api/files-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesRoute = ApiFilesRouteImport.update({
  id: '/api/files',
  path: '/api/files',
  getParentRoute: () => rootRouteImport,
} as any)
const publicVersionRoute = publicVersionRouteImport.update({
  id: '/version',
  path: '/version',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicThemeRoute = publicThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicAboutRoute = publicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => publicRouteRoute,
} as any)
const app2Dashboard2Route = app2Dashboard2RouteImport.update({
  id: '/dashboard2',
  path: '/dashboard2',
  getParentRoute: () => app2RouteRoute,
} as any)
const appRenewalsRoute = appRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => appRouteRoute,
} as any)
const appOrdersRoute = appOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => appRouteRoute,
} as any)
const ApiChatIndexRoute = ApiChatIndexRouteImport.update({
  id: '/api/chat/',
  path: '/api/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const appSupportIndexRoute = appSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardIndexRoute = appDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => appRouteRoute,
} as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/api/health/live',
  path: '/api/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthPathRoute = publicAuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => publicRouteRoute,
} as any)
const appSettingsNotificationsRoute =
  appSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => appRouteRoute,
  } as any)
const appSettingsPageRoute = appSettingsPageRouteImport.update({
  id: '/settings/$page',
  path: '/settings/$page',
  getParentRoute: () => appRouteRoute,
} as any)
const appReportsPageRoute = appReportsPageRouteImport.update({
  id: '/reports/$page',
  path: '/reports/$page',
  getParentRoute: () => appRouteRoute,
} as any)
const appPlaygroundWorkflowRoute = appPlaygroundWorkflowRouteImport.update({
  id: '/playground/workflow',
  path: '/playground/workflow',
  getParentRoute: () => appRouteRoute,
} as any)
const appPlaygroundTestRoute = appPlaygroundTestRouteImport.update({
  id: '/playground/test',
  path: '/playground/test',
  getParentRoute: () => appRouteRoute,
} as any)
const appPlaygroundFormDemoRoute = appPlaygroundFormDemoRouteImport.update({
  id: '/playground/form-demo',
  path: '/playground/form-demo',
  getParentRoute: () => appRouteRoute,
} as any)
const appPlaygroundFilesRoute = appPlaygroundFilesRouteImport.update({
  id: '/playground/files',
  path: '/playground/files',
  getParentRoute: () => appRouteRoute,
} as any)
const appPlaygroundErrorRoute = appPlaygroundErrorRouteImport.update({
  id: '/playground/error',
  path: '/playground/error',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardPageRoute = appDashboardPageRouteImport.update({
  id: '/dashboard/$page',
  path: '/dashboard/$page',
  getParentRoute: () => appRouteRoute,
} as any)
const appAdminPageRoute = appAdminPageRouteImport.update({
  id: '/admin/$page',
  path: '/admin/$page',
  getParentRoute: () => appRouteRoute,
} as any)
const appsecurityUserPathRoute = appsecurityUserPathRouteImport.update({
  id: '/(security)/user/$path',
  path: '/user/$path',
  getParentRoute: () => appRouteRoute,
} as any)
const appsecurityOrganizationPathRoute =
  appsecurityOrganizationPathRouteImport.update({
    id: '/(security)/organization/$path',
    path: '/organization/$path',
    getParentRoute: () => appRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/orders': typeof appOrdersRoute
  '/renewals': typeof appRenewalsRoute
  '/dashboard2': typeof app2Dashboard2Route
  '/about': typeof publicAboutRoute
  '/theme': typeof publicThemeRoute
  '/version': typeof publicVersionRoute
  '/api/files': typeof ApiFilesRoute
  '/api/files-test': typeof ApiFilesTestRoute
  '/api/images': typeof ApiImagesRoute
  '/api/orders': typeof ApiOrdersRoute
  '/': typeof publicIndexRoute
  '/admin/$page': typeof appAdminPageRoute
  '/dashboard/$page': typeof appDashboardPageRoute
  '/playground/error': typeof appPlaygroundErrorRoute
  '/playground/files': typeof appPlaygroundFilesRoute
  '/playground/form-demo': typeof appPlaygroundFormDemoRoute
  '/playground/test': typeof appPlaygroundTestRoute
  '/playground/workflow': typeof appPlaygroundWorkflowRoute
  '/reports/$page': typeof appReportsPageRoute
  '/settings/$page': typeof appSettingsPageRoute
  '/settings/notifications': typeof appSettingsNotificationsRoute
  '/auth/$path': typeof publicAuthPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/dashboard/': typeof appDashboardIndexRoute
  '/support/': typeof appSupportIndexRoute
  '/api/chat/': typeof ApiChatIndexRoute
  '/organization/$path': typeof appsecurityOrganizationPathRoute
  '/user/$path': typeof appsecurityUserPathRoute
}
export interface FileRoutesByTo {
  '/orders': typeof appOrdersRoute
  '/renewals': typeof appRenewalsRoute
  '/dashboard2': typeof app2Dashboard2Route
  '/about': typeof publicAboutRoute
  '/theme': typeof publicThemeRoute
  '/version': typeof publicVersionRoute
  '/api/files': typeof ApiFilesRoute
  '/api/files-test': typeof ApiFilesTestRoute
  '/api/images': typeof ApiImagesRoute
  '/api/orders': typeof ApiOrdersRoute
  '/': typeof publicIndexRoute
  '/admin/$page': typeof appAdminPageRoute
  '/dashboard/$page': typeof appDashboardPageRoute
  '/playground/error': typeof appPlaygroundErrorRoute
  '/playground/files': typeof appPlaygroundFilesRoute
  '/playground/form-demo': typeof appPlaygroundFormDemoRoute
  '/playground/test': typeof appPlaygroundTestRoute
  '/playground/workflow': typeof appPlaygroundWorkflowRoute
  '/reports/$page': typeof appReportsPageRoute
  '/settings/$page': typeof appSettingsPageRoute
  '/settings/notifications': typeof appSettingsNotificationsRoute
  '/auth/$path': typeof publicAuthPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/dashboard': typeof appDashboardIndexRoute
  '/support': typeof appSupportIndexRoute
  '/api/chat': typeof ApiChatIndexRoute
  '/organization/$path': typeof appsecurityOrganizationPathRoute
  '/user/$path': typeof appsecurityUserPathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app2)': typeof app2RouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(app)/orders': typeof appOrdersRoute
  '/(app)/renewals': typeof appRenewalsRoute
  '/(app2)/dashboard2': typeof app2Dashboard2Route
  '/(public)/about': typeof publicAboutRoute
  '/(public)/theme': typeof publicThemeRoute
  '/(public)/version': typeof publicVersionRoute
  '/api/files': typeof ApiFilesRoute
  '/api/files-test': typeof ApiFilesTestRoute
  '/api/images': typeof ApiImagesRoute
  '/api/orders': typeof ApiOrdersRoute
  '/(public)/': typeof publicIndexRoute
  '/(app)/admin/$page': typeof appAdminPageRoute
  '/(app)/dashboard/$page': typeof appDashboardPageRoute
  '/(app)/playground/error': typeof appPlaygroundErrorRoute
  '/(app)/playground/files': typeof appPlaygroundFilesRoute
  '/(app)/playground/form-demo': typeof appPlaygroundFormDemoRoute
  '/(app)/playground/test': typeof appPlaygroundTestRoute
  '/(app)/playground/workflow': typeof appPlaygroundWorkflowRoute
  '/(app)/reports/$page': typeof appReportsPageRoute
  '/(app)/settings/$page': typeof appSettingsPageRoute
  '/(app)/settings/notifications': typeof appSettingsNotificationsRoute
  '/(public)/auth/$path': typeof publicAuthPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/(app)/dashboard/': typeof appDashboardIndexRoute
  '/(app)/support/': typeof appSupportIndexRoute
  '/api/chat/': typeof ApiChatIndexRoute
  '/(app)/(security)/organization/$path': typeof appsecurityOrganizationPathRoute
  '/(app)/(security)/user/$path': typeof appsecurityUserPathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/orders'
    | '/renewals'
    | '/dashboard2'
    | '/about'
    | '/theme'
    | '/version'
    | '/api/files'
    | '/api/files-test'
    | '/api/images'
    | '/api/orders'
    | '/'
    | '/admin/$page'
    | '/dashboard/$page'
    | '/playground/error'
    | '/playground/files'
    | '/playground/form-demo'
    | '/playground/test'
    | '/playground/workflow'
    | '/reports/$page'
    | '/settings/$page'
    | '/settings/notifications'
    | '/auth/$path'
    | '/api/auth/$'
    | '/api/health/live'
    | '/dashboard/'
    | '/support/'
    | '/api/chat/'
    | '/organization/$path'
    | '/user/$path'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/orders'
    | '/renewals'
    | '/dashboard2'
    | '/about'
    | '/theme'
    | '/version'
    | '/api/files'
    | '/api/files-test'
    | '/api/images'
    | '/api/orders'
    | '/'
    | '/admin/$page'
    | '/dashboard/$page'
    | '/playground/error'
    | '/playground/files'
    | '/playground/form-demo'
    | '/playground/test'
    | '/playground/workflow'
    | '/reports/$page'
    | '/settings/$page'
    | '/settings/notifications'
    | '/auth/$path'
    | '/api/auth/$'
    | '/api/health/live'
    | '/dashboard'
    | '/support'
    | '/api/chat'
    | '/organization/$path'
    | '/user/$path'
  id:
    | '__root__'
    | '/(app)'
    | '/(app2)'
    | '/(public)'
    | '/(app)/orders'
    | '/(app)/renewals'
    | '/(app2)/dashboard2'
    | '/(public)/about'
    | '/(public)/theme'
    | '/(public)/version'
    | '/api/files'
    | '/api/files-test'
    | '/api/images'
    | '/api/orders'
    | '/(public)/'
    | '/(app)/admin/$page'
    | '/(app)/dashboard/$page'
    | '/(app)/playground/error'
    | '/(app)/playground/files'
    | '/(app)/playground/form-demo'
    | '/(app)/playground/test'
    | '/(app)/playground/workflow'
    | '/(app)/reports/$page'
    | '/(app)/settings/$page'
    | '/(app)/settings/notifications'
    | '/(public)/auth/$path'
    | '/api/auth/$'
    | '/api/health/live'
    | '/(app)/dashboard/'
    | '/(app)/support/'
    | '/api/chat/'
    | '/(app)/(security)/organization/$path'
    | '/(app)/(security)/user/$path'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  app2RouteRoute: typeof app2RouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  ApiFilesRoute: typeof ApiFilesRoute
  ApiFilesTestRoute: typeof ApiFilesTestRoute
  ApiImagesRoute: typeof ApiImagesRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
  ApiChatIndexRoute: typeof ApiChatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app2)': {
      id: '/(app2)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof app2RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images': {
      id: '/api/images'
      path: '/api/images'
      fullPath: '/api/images'
      preLoaderRoute: typeof ApiImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files-test': {
      id: '/api/files-test'
      path: '/api/files-test'
      fullPath: '/api/files-test'
      preLoaderRoute: typeof ApiFilesTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files': {
      id: '/api/files'
      path: '/api/files'
      fullPath: '/api/files'
      preLoaderRoute: typeof ApiFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/version': {
      id: '/(public)/version'
      path: '/version'
      fullPath: '/version'
      preLoaderRoute: typeof publicVersionRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/theme': {
      id: '/(public)/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof publicThemeRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(app2)/dashboard2': {
      id: '/(app2)/dashboard2'
      path: '/dashboard2'
      fullPath: '/dashboard2'
      preLoaderRoute: typeof app2Dashboard2RouteImport
      parentRoute: typeof app2RouteRoute
    }
    '/(app)/renewals': {
      id: '/(app)/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof appRenewalsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/orders': {
      id: '/(app)/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof appOrdersRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/chat/': {
      id: '/api/chat/'
      path: '/api/chat'
      fullPath: '/api/chat/'
      preLoaderRoute: typeof ApiChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/support/': {
      id: '/(app)/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof appSupportIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard/': {
      id: '/(app)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof appDashboardIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/health/live': {
      id: '/api/health/live'
      path: '/api/health/live'
      fullPath: '/api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/auth/$path': {
      id: '/(public)/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof publicAuthPathRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(app)/settings/notifications': {
      id: '/(app)/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof appSettingsNotificationsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/$page': {
      id: '/(app)/settings/$page'
      path: '/settings/$page'
      fullPath: '/settings/$page'
      preLoaderRoute: typeof appSettingsPageRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/reports/$page': {
      id: '/(app)/reports/$page'
      path: '/reports/$page'
      fullPath: '/reports/$page'
      preLoaderRoute: typeof appReportsPageRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/playground/workflow': {
      id: '/(app)/playground/workflow'
      path: '/playground/workflow'
      fullPath: '/playground/workflow'
      preLoaderRoute: typeof appPlaygroundWorkflowRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/playground/test': {
      id: '/(app)/playground/test'
      path: '/playground/test'
      fullPath: '/playground/test'
      preLoaderRoute: typeof appPlaygroundTestRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/playground/form-demo': {
      id: '/(app)/playground/form-demo'
      path: '/playground/form-demo'
      fullPath: '/playground/form-demo'
      preLoaderRoute: typeof appPlaygroundFormDemoRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/playground/files': {
      id: '/(app)/playground/files'
      path: '/playground/files'
      fullPath: '/playground/files'
      preLoaderRoute: typeof appPlaygroundFilesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/playground/error': {
      id: '/(app)/playground/error'
      path: '/playground/error'
      fullPath: '/playground/error'
      preLoaderRoute: typeof appPlaygroundErrorRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard/$page': {
      id: '/(app)/dashboard/$page'
      path: '/dashboard/$page'
      fullPath: '/dashboard/$page'
      preLoaderRoute: typeof appDashboardPageRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/admin/$page': {
      id: '/(app)/admin/$page'
      path: '/admin/$page'
      fullPath: '/admin/$page'
      preLoaderRoute: typeof appAdminPageRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(security)/user/$path': {
      id: '/(app)/(security)/user/$path'
      path: '/user/$path'
      fullPath: '/user/$path'
      preLoaderRoute: typeof appsecurityUserPathRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/(security)/organization/$path': {
      id: '/(app)/(security)/organization/$path'
      path: '/organization/$path'
      fullPath: '/organization/$path'
      preLoaderRoute: typeof appsecurityOrganizationPathRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appOrdersRoute: typeof appOrdersRoute
  appRenewalsRoute: typeof appRenewalsRoute
  appAdminPageRoute: typeof appAdminPageRoute
  appDashboardPageRoute: typeof appDashboardPageRoute
  appPlaygroundErrorRoute: typeof appPlaygroundErrorRoute
  appPlaygroundFilesRoute: typeof appPlaygroundFilesRoute
  appPlaygroundFormDemoRoute: typeof appPlaygroundFormDemoRoute
  appPlaygroundTestRoute: typeof appPlaygroundTestRoute
  appPlaygroundWorkflowRoute: typeof appPlaygroundWorkflowRoute
  appReportsPageRoute: typeof appReportsPageRoute
  appSettingsPageRoute: typeof appSettingsPageRoute
  appSettingsNotificationsRoute: typeof appSettingsNotificationsRoute
  appDashboardIndexRoute: typeof appDashboardIndexRoute
  appSupportIndexRoute: typeof appSupportIndexRoute
  appsecurityOrganizationPathRoute: typeof appsecurityOrganizationPathRoute
  appsecurityUserPathRoute: typeof appsecurityUserPathRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appOrdersRoute: appOrdersRoute,
  appRenewalsRoute: appRenewalsRoute,
  appAdminPageRoute: appAdminPageRoute,
  appDashboardPageRoute: appDashboardPageRoute,
  appPlaygroundErrorRoute: appPlaygroundErrorRoute,
  appPlaygroundFilesRoute: appPlaygroundFilesRoute,
  appPlaygroundFormDemoRoute: appPlaygroundFormDemoRoute,
  appPlaygroundTestRoute: appPlaygroundTestRoute,
  appPlaygroundWorkflowRoute: appPlaygroundWorkflowRoute,
  appReportsPageRoute: appReportsPageRoute,
  appSettingsPageRoute: appSettingsPageRoute,
  appSettingsNotificationsRoute: appSettingsNotificationsRoute,
  appDashboardIndexRoute: appDashboardIndexRoute,
  appSupportIndexRoute: appSupportIndexRoute,
  appsecurityOrganizationPathRoute: appsecurityOrganizationPathRoute,
  appsecurityUserPathRoute: appsecurityUserPathRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface app2RouteRouteChildren {
  app2Dashboard2Route: typeof app2Dashboard2Route
}

const app2RouteRouteChildren: app2RouteRouteChildren = {
  app2Dashboard2Route: app2Dashboard2Route,
}

const app2RouteRouteWithChildren = app2RouteRoute._addFileChildren(
  app2RouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicAboutRoute: typeof publicAboutRoute
  publicThemeRoute: typeof publicThemeRoute
  publicVersionRoute: typeof publicVersionRoute
  publicIndexRoute: typeof publicIndexRoute
  publicAuthPathRoute: typeof publicAuthPathRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicAboutRoute: publicAboutRoute,
  publicThemeRoute: publicThemeRoute,
  publicVersionRoute: publicVersionRoute,
  publicIndexRoute: publicIndexRoute,
  publicAuthPathRoute: publicAuthPathRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  app2RouteRoute: app2RouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  ApiFilesRoute: ApiFilesRoute,
  ApiFilesTestRoute: ApiFilesTestRoute,
  ApiImagesRoute: ApiImagesRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiHealthLiveRoute: ApiHealthLiveRoute,
  ApiChatIndexRoute: ApiChatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
