/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as app2RouteRouteImport } from './routes/(app2)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicVersionRouteImport } from './routes/(public)/version'
import { Route as publicThemeRouteImport } from './routes/(public)/theme'
import { Route as publicAboutRouteImport } from './routes/(public)/about'
import { Route as app2Dashboard2RouteImport } from './routes/(app2)/dashboard2'
import { Route as appDashboardIndexRouteImport } from './routes/(app)/dashboard.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as publicAuthPathRouteImport } from './routes/(public)/auth/$path'
import { Route as appSettingsPathRouteImport } from './routes/(app)/settings/$path'
import { Route as appOrganizationPathRouteImport } from './routes/(app)/organization/$path'
import { Route as appDashboardPageRouteImport } from './routes/(app)/dashboard.$page'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const app2RouteRoute = app2RouteRouteImport.update({
  id: '/(app2)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicVersionRoute = publicVersionRouteImport.update({
  id: '/version',
  path: '/version',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicThemeRoute = publicThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicAboutRoute = publicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => publicRouteRoute,
} as any)
const app2Dashboard2Route = app2Dashboard2RouteImport.update({
  id: '/dashboard2',
  path: '/dashboard2',
  getParentRoute: () => app2RouteRoute,
} as any)
const appDashboardIndexRoute = appDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => appRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthPathRoute = publicAuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => publicRouteRoute,
} as any)
const appSettingsPathRoute = appSettingsPathRouteImport.update({
  id: '/settings/$path',
  path: '/settings/$path',
  getParentRoute: () => appRouteRoute,
} as any)
const appOrganizationPathRoute = appOrganizationPathRouteImport.update({
  id: '/organization/$path',
  path: '/organization/$path',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardPageRoute = appDashboardPageRouteImport.update({
  id: '/dashboard/$page',
  path: '/dashboard/$page',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard2': typeof app2Dashboard2Route
  '/about': typeof publicAboutRoute
  '/theme': typeof publicThemeRoute
  '/version': typeof publicVersionRoute
  '/': typeof publicIndexRoute
  '/dashboard/$page': typeof appDashboardPageRoute
  '/organization/$path': typeof appOrganizationPathRoute
  '/settings/$path': typeof appSettingsPathRoute
  '/auth/$path': typeof publicAuthPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof appDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard2': typeof app2Dashboard2Route
  '/about': typeof publicAboutRoute
  '/theme': typeof publicThemeRoute
  '/version': typeof publicVersionRoute
  '/': typeof publicIndexRoute
  '/dashboard/$page': typeof appDashboardPageRoute
  '/organization/$path': typeof appOrganizationPathRoute
  '/settings/$path': typeof appSettingsPathRoute
  '/auth/$path': typeof publicAuthPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof appDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app2)': typeof app2RouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(app2)/dashboard2': typeof app2Dashboard2Route
  '/(public)/about': typeof publicAboutRoute
  '/(public)/theme': typeof publicThemeRoute
  '/(public)/version': typeof publicVersionRoute
  '/(public)/': typeof publicIndexRoute
  '/(app)/dashboard/$page': typeof appDashboardPageRoute
  '/(app)/organization/$path': typeof appOrganizationPathRoute
  '/(app)/settings/$path': typeof appSettingsPathRoute
  '/(public)/auth/$path': typeof publicAuthPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(app)/dashboard/': typeof appDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard2'
    | '/about'
    | '/theme'
    | '/version'
    | '/'
    | '/dashboard/$page'
    | '/organization/$path'
    | '/settings/$path'
    | '/auth/$path'
    | '/api/auth/$'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard2'
    | '/about'
    | '/theme'
    | '/version'
    | '/'
    | '/dashboard/$page'
    | '/organization/$path'
    | '/settings/$path'
    | '/auth/$path'
    | '/api/auth/$'
    | '/dashboard'
  id:
    | '__root__'
    | '/(app)'
    | '/(app2)'
    | '/(public)'
    | '/(app2)/dashboard2'
    | '/(public)/about'
    | '/(public)/theme'
    | '/(public)/version'
    | '/(public)/'
    | '/(app)/dashboard/$page'
    | '/(app)/organization/$path'
    | '/(app)/settings/$path'
    | '/(public)/auth/$path'
    | '/api/auth/$'
    | '/(app)/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  app2RouteRoute: typeof app2RouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app2)': {
      id: '/(app2)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof app2RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/version': {
      id: '/(public)/version'
      path: '/version'
      fullPath: '/version'
      preLoaderRoute: typeof publicVersionRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/theme': {
      id: '/(public)/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof publicThemeRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(app2)/dashboard2': {
      id: '/(app2)/dashboard2'
      path: '/dashboard2'
      fullPath: '/dashboard2'
      preLoaderRoute: typeof app2Dashboard2RouteImport
      parentRoute: typeof app2RouteRoute
    }
    '/(app)/dashboard/': {
      id: '/(app)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof appDashboardIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/auth/$path': {
      id: '/(public)/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof publicAuthPathRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(app)/settings/$path': {
      id: '/(app)/settings/$path'
      path: '/settings/$path'
      fullPath: '/settings/$path'
      preLoaderRoute: typeof appSettingsPathRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/organization/$path': {
      id: '/(app)/organization/$path'
      path: '/organization/$path'
      fullPath: '/organization/$path'
      preLoaderRoute: typeof appOrganizationPathRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard/$page': {
      id: '/(app)/dashboard/$page'
      path: '/dashboard/$page'
      fullPath: '/dashboard/$page'
      preLoaderRoute: typeof appDashboardPageRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appDashboardPageRoute: typeof appDashboardPageRoute
  appOrganizationPathRoute: typeof appOrganizationPathRoute
  appSettingsPathRoute: typeof appSettingsPathRoute
  appDashboardIndexRoute: typeof appDashboardIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appDashboardPageRoute: appDashboardPageRoute,
  appOrganizationPathRoute: appOrganizationPathRoute,
  appSettingsPathRoute: appSettingsPathRoute,
  appDashboardIndexRoute: appDashboardIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface app2RouteRouteChildren {
  app2Dashboard2Route: typeof app2Dashboard2Route
}

const app2RouteRouteChildren: app2RouteRouteChildren = {
  app2Dashboard2Route: app2Dashboard2Route,
}

const app2RouteRouteWithChildren = app2RouteRoute._addFileChildren(
  app2RouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicAboutRoute: typeof publicAboutRoute
  publicThemeRoute: typeof publicThemeRoute
  publicVersionRoute: typeof publicVersionRoute
  publicIndexRoute: typeof publicIndexRoute
  publicAuthPathRoute: typeof publicAuthPathRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicAboutRoute: publicAboutRoute,
  publicThemeRoute: publicThemeRoute,
  publicVersionRoute: publicVersionRoute,
  publicIndexRoute: publicIndexRoute,
  publicAuthPathRoute: publicAuthPathRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  app2RouteRoute: app2RouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
