/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicThemeRouteImport } from './routes/(public)/theme'
import { Route as publicI18nRouteImport } from './routes/(public)/i18n'
import { Route as publicAboutRouteImport } from './routes/(public)/about'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as publicAuthPathRouteImport } from './routes/(public)/auth/$path'
import { Route as appSettingsPathRouteImport } from './routes/(app)/settings/$path'
import { Route as appOrganizationSlugPathRouteImport } from './routes/(app)/organization/$slug/$path'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicThemeRoute = publicThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicI18nRoute = publicI18nRouteImport.update({
  id: '/i18n',
  path: '/i18n',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicAboutRoute = publicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => publicRouteRoute,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthPathRoute = publicAuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => publicRouteRoute,
} as any)
const appSettingsPathRoute = appSettingsPathRouteImport.update({
  id: '/settings/$path',
  path: '/settings/$path',
  getParentRoute: () => appRouteRoute,
} as any)
const appOrganizationSlugPathRoute = appOrganizationSlugPathRouteImport.update({
  id: '/organization/$slug/$path',
  path: '/organization/$slug/$path',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof appDashboardRoute
  '/about': typeof publicAboutRoute
  '/i18n': typeof publicI18nRoute
  '/theme': typeof publicThemeRoute
  '/': typeof publicIndexRoute
  '/settings/$path': typeof appSettingsPathRoute
  '/auth/$path': typeof publicAuthPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organization/$slug/$path': typeof appOrganizationSlugPathRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof appDashboardRoute
  '/about': typeof publicAboutRoute
  '/i18n': typeof publicI18nRoute
  '/theme': typeof publicThemeRoute
  '/': typeof publicIndexRoute
  '/settings/$path': typeof appSettingsPathRoute
  '/auth/$path': typeof publicAuthPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organization/$slug/$path': typeof appOrganizationSlugPathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(app)/dashboard': typeof appDashboardRoute
  '/(public)/about': typeof publicAboutRoute
  '/(public)/i18n': typeof publicI18nRoute
  '/(public)/theme': typeof publicThemeRoute
  '/(public)/': typeof publicIndexRoute
  '/(app)/settings/$path': typeof appSettingsPathRoute
  '/(public)/auth/$path': typeof publicAuthPathRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(app)/organization/$slug/$path': typeof appOrganizationSlugPathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/about'
    | '/i18n'
    | '/theme'
    | '/'
    | '/settings/$path'
    | '/auth/$path'
    | '/api/auth/$'
    | '/organization/$slug/$path'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/about'
    | '/i18n'
    | '/theme'
    | '/'
    | '/settings/$path'
    | '/auth/$path'
    | '/api/auth/$'
    | '/organization/$slug/$path'
  id:
    | '__root__'
    | '/(app)'
    | '/(public)'
    | '/(app)/dashboard'
    | '/(public)/about'
    | '/(public)/i18n'
    | '/(public)/theme'
    | '/(public)/'
    | '/(app)/settings/$path'
    | '/(public)/auth/$path'
    | '/api/auth/$'
    | '/(app)/organization/$slug/$path'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/theme': {
      id: '/(public)/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof publicThemeRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/i18n': {
      id: '/(public)/i18n'
      path: '/i18n'
      fullPath: '/i18n'
      preLoaderRoute: typeof publicI18nRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/auth/$path': {
      id: '/(public)/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof publicAuthPathRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(app)/settings/$path': {
      id: '/(app)/settings/$path'
      path: '/settings/$path'
      fullPath: '/settings/$path'
      preLoaderRoute: typeof appSettingsPathRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/organization/$slug/$path': {
      id: '/(app)/organization/$slug/$path'
      path: '/organization/$slug/$path'
      fullPath: '/organization/$slug/$path'
      preLoaderRoute: typeof appOrganizationSlugPathRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appDashboardRoute: typeof appDashboardRoute
  appSettingsPathRoute: typeof appSettingsPathRoute
  appOrganizationSlugPathRoute: typeof appOrganizationSlugPathRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appDashboardRoute: appDashboardRoute,
  appSettingsPathRoute: appSettingsPathRoute,
  appOrganizationSlugPathRoute: appOrganizationSlugPathRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicAboutRoute: typeof publicAboutRoute
  publicI18nRoute: typeof publicI18nRoute
  publicThemeRoute: typeof publicThemeRoute
  publicIndexRoute: typeof publicIndexRoute
  publicAuthPathRoute: typeof publicAuthPathRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicAboutRoute: publicAboutRoute,
  publicI18nRoute: publicI18nRoute,
  publicThemeRoute: publicThemeRoute,
  publicIndexRoute: publicIndexRoute,
  publicAuthPathRoute: publicAuthPathRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
