/* eslint-disable */
// @ts-nocheck
// biome-ignore-all lint: auto-generated
// Auto-generated by @vite-env/core
// Do not edit manually — re-generated on every dev server start and build

declare module 'virtual:env/client' {
  const env: {
    readonly VITE_BETTER_AUTH_URL: string
    readonly VITE_GOOGLE_CLIENT_ID?: string
    readonly VITE_TURNSTILE_ENABLED: boolean
    readonly VITE_TURNSTILE_SITE_KEY: string
  }
  export { env }
  export default env
}

declare module 'virtual:env/server' {
  const env: {
    readonly BETTER_AUTH_SECRET: string
    readonly BETTER_AUTH_ADMINS: string
    readonly BETTER_AUTH_JWT_EXPIRATION_TIME: string
    readonly GOOGLE_CLIENT_SECRET?: string
    readonly GITHUB_CLIENT_ID?: string
    readonly GITHUB_CLIENT_SECRET?: string
    readonly TURNSTILE_SECRET_KEY: string
    readonly VITE_BETTER_AUTH_URL: string
    readonly VITE_GOOGLE_CLIENT_ID?: string
    readonly VITE_TURNSTILE_ENABLED: boolean
    readonly VITE_TURNSTILE_SITE_KEY: string
  }
  export { env }
  export default env
}
