/* eslint-disable */
// @ts-nocheck
// biome-ignore-all lint: auto-generated
// Auto-generated by @vite-env/core
// Do not edit manually — re-generated on every dev server start and build

declare module 'virtual:env/client' {
  const env: {

  }
  export { env }
  export default env
}

declare module 'virtual:env/server' {
  const env: {
    readonly EMAIL_FROM: string
    readonly CONTACT_EMAIL?: string
    readonly EMAIL_TO: string
    readonly RESEND_API_KEY?: string
    readonly RESEND_WEBHOOK_SECRET?: string
    readonly RESEND_AUDIENCE_ID?: string
    readonly RESEND_TEMPLATE_ID?: string
    readonly CONFIRM_REDIRECT_URL?: string
    readonly SENDGRID_API_KEY?: string
    readonly PLUNK_API_KEY?: string
    readonly POSTMARK_API_KEY?: string
    readonly SMTP_HOST: string
    readonly SMTP_PORT: number
    readonly SMTP_SECURE: boolean
    readonly SMTP_USER?: string
    readonly SMTP_PASS?: string
  }
  export { env }
  export default env
}
