/* eslint-disable */
// @ts-nocheck
// biome-ignore-all lint: auto-generated
// Auto-generated by @vite-env/core
// Do not edit manually — re-generated on every dev server start and build

declare module 'virtual:env/client' {
  const env: {
    readonly VITE_APP_NAME: string
    readonly VITE_CONSOLE_URL: string
  }
  export { env }
  export default env
}

declare module 'virtual:env/server' {
  const env: {
    readonly DATABASE_URL: string
    readonly DB_POOL_SIZE: number
    readonly BETTER_AUTH_ADMINS: string
    readonly BETTER_AUTH_ADMIN_EMAIL: string
    readonly BETTER_AUTH_ADMIN_PASSWORD: string
    readonly SHARED_ORGANIZATION_ID: string
    readonly CONTACT_EMAIL: string
    readonly VITE_APP_NAME: string
    readonly VITE_CONSOLE_URL: string
  }
  export { env }
  export default env
}
